# Author: Bell (bell@softbell.net)
# Bell Soft Network Infra 전용 CI/CD 파이프라인 정의
#
# [필수 구성 변수]
# KUBE_CONTEXT: {KAS 가 연결된 깃랩 repo 주소}:{에이전트명} (ex. BSN/bsn-primary-agent:primary-agent})
# KUBE_NAMESPACE: kubernetes 배포에 사용할 기본 네임스페이스
# KUBE_STAGING_NAMESPACE: kubernetes 스테이징 배포에 사용할 네임스페이스
# KUBE_PRODUCTION_NAMESPACE: kubernetes 프로덕션 배포에 사용할 네임스페이스
# KUBE_INGRESS_BASE_DOMAIN: kubernetes 내 ingress 에 등록할 기본 도메인
#  (ex. `bell-safe-house.bellsoft.net` 으로 설정 후 develop 브랜치 배포시 `https://develop.bell-safe-house.bellsoft.net` 으로 등록됨)
#
# [설정 가능한 변수]
# - NODE_VERSION: node 버전
# - TEST_DISABLED: 테스트 비활성 (값 설정 시)
# - BUILD_DISABLED: 빌드 비활성 (값 설정 시)
# - DEPLOY_DISABLED: 배포 비활성 (값 설정 시)
# - CODE_QUALITY_DISABLED: 코드 퀄리티 측정 비활성 (값 설정 시)

variables:
  NODE_VERSION: 16-alpine

stages:
  - test
  - build
  - review
  - staging
  - deploy
  - cleanup

include:
  - local: /.gitlab/ci/jobs/templates/default.gitlab-ci.yaml # 공통 구성요소 템플릿
  - local: /.gitlab/ci/jobs/test.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/build.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/review.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/staging.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/deploy.gitlab-ci.yaml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
