#!/bin/bash

# PRINT CURRENT ENVIRONMENT
echo "-- Kubernetes 리소스 설정 --"
echo "KUBERNETES_RESOURCE_PATH: ${KUBERNETES_RESOURCE_PATH}"
echo "KUBERNETES_DEPLOY_YAML_PATH: ${KUBERNETES_DEPLOY_YAML_PATH}"
echo "KUBERNETES_HOST_SOURCE_MOUNT_PATH: ${KUBERNETES_HOST_SOURCE_MOUNT_PATH}"
echo
